### ISSUE TITLE
Add reference to NPM version

### ISSUE THREAD

**Issue by inttter** [inttter/md-badges#137]
https://github.com/inttter/mdbadges-cli

**Comment by NormTurtle** [comment]
can you please elaborate what you actually want?

**Comment by inttter** [comment]
just linking to **[this](https://github.com/inttter/mdbadges-cli)** repository by saying something like "check out the npm version here" or something along those lines.

**Comment by NormTurtle** [comment]
![image](https://github.com/inttter/md-badges/assets/108952834/7e61d0cb-0f5f-4f81-af40-042ef2e3f1df)
like this?

**Comment by inttter** [comment]
yeah, you could add it as a badge if you'd like.

**Comment by inttter** [comment]
added in https://github.com/inttter/md-badges/commit/2d66af2f3a0e560d2ef3c095081e673cd5134b36
